### ISSUE TITLE
SCP-1797 meat constantly giving errors when Meat Optimisation Mods are used

### ISSUE THREAD

**Issue by Cramoisi-San** [DeeMainiac/SCR_Mod#11]
**Describe the bug**
When using this mod and a mod that optimises meats together, the log will constantly open with a looping error "Looked for nonexistent key SCR_SCP1797Meat in counted resources." It keeps opening constantly until "Auto-open" is off, but otherwise it has no effect on gameplay.
( Looked for nonexistent key SCR_SCP1797Meat in counted resources.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch0 (string)
RimWorld.ResourceCounter:GetCount (Verse.ThingDef)
RimWorld.ResourceCounter:GetCountIn (Verse.ThingCategoryDef)
RimWorld.ResourceCounter:GetCountIn (Verse.ThingCategoryDef)
RimWorld.Listing_ResourceReadout:DoCategory (Verse.TreeNode_ThingCategory,int,int)
RimWorld.ResourceReadout:DoReadoutCategorized (UnityEngine.Rect)
RimWorld.ResourceReadout:ResourceReadoutOnGUI ()
(wrapper dynamic-method) RimWorld.MapInterface:RimWorld.MapInterface.MapInterfaceOnGUI_BeforeMainTabs_Patch1 (RimWorld.MapInterface)
(wrapper dynamic-method) RimWorld.UIRoot_Play:RimWorld.UIRoot_Play.UIRootOnGUI_Patch1 (RimWorld.UIRoot_Play)
(wrapper dynamic-method) Verse.Root:Verse.Root.OnGUI_Patch1 (Verse.Root) )

**To Reproduce**
1. Use both this mod, and a mod that optimises meats, like Optimization: Meats - C# Edition ( https://steamcommunity.com/sharedfiles/filedetails/?id=2542931556 )
2. Activate dev mode to see log
3. See looping and stacking error message

**Expected behavior**
The error shouldn't happen, or at the very least the error shouldn't appear and open log every ~5 seconds.

**Screenshots**
Screenshots are not needed, nothing visible other than the logs happens.

**Mod Version:**
[Steam Workshop, Latest version]

**Modlist**
- Secure Protect Rimworld [Steam Workshop, Latest version]
- Optimization: Meats - C# Edition [Steam Workshop, Latest version]

**Additional context**
The error has no effect on gameplay other than forcing the player to turn off auto opening of log, which may hinder more important issue-finding.

**Comment by DeeMainiac** [comment]
Thanks for making a report! 
I can confirm this bug is happening, and it does have an effect on gameplay. SCP-1797 (Kitten Flu) meat is used in a recipe to make samples of SCP-1797 (that you can feed to pawns to give them SCP-1797). 
Optimization: Meats - C# Edition erroneously removes this meat and thus, errors. You can't make the samples without the meat. I'll have to think of a way to get around this without harming others' saves.

**Comment by Cramoisi-San** [comment]
I do know that this mod does not remove anything that's not classified as a regular meat, be it insect or "bad" meat. Maybe you could do something with that ?

**Comment by DeeMainiac** [comment]
Yea, that's probably what I'll do, make it into nonregular meat.

**Comment by Cramoisi-San** [comment]
I mean, it's meat that gives you an anomalous disease when eating it, so it must be non-standard

**Comment by DeeMainiac** [comment]
Alright, I think I've fixed this issue. Feel free to download from this GitHub or wait until I post the updated version on Steam. I plan on probably doing that later today, but who knows.
