### ISSUE TITLE
Bug with the walls and doors added by the mod

### ISSUE THREAD

**Issue by evrymetul** [DeeMainiac/SCR_Mod#6]
**Describe the bug**
You can build both types of doors and walls without the required research, and steel strengthened walls and plasteel reinforced walls have the same amount of hit points.

**To Reproduce**
Started a new colony and saw both wall types and door types were available. Checked the hit points of both doors, and noticed they were both 600 when the material used was steel. Checked the research tab to see if both researches were automatically unlocked, but they weren't. Checked the ini file to see if there weren't any prerequisites, but there were. Deleted <recipeMaker> and </recipeMaker> in the ini, but that only caused errors on startup and no change.

**Expected behavior**
Both wall types are have research prerequisites, but for some reason, they are being ignored. One wall type requires a rarer resource (plasteel), but there is no benefit to building it compared to the first type.

**Screenshots**

**Mod Version:**
Steam Workshop Feb 6 @ 12:52pm

**Modlist**
No mods besides the dlc, Harmony, and Secure Contain Rimworld.

**Additional context**

**Comment by DeeMainiac** [comment]
Thanks for making a report! I can confirm this bug is occurring. I'll see if I can figure out why this happens.

**Comment by DeeMainiac** [comment]
fixed in an update on the main branch. I will update the steam build this weekend or so.
