### ISSUE TITLE
RAM Incident at Site TSP: Link

### ISSUE THREAD

**Issue by TurtleShroom** [DeeMainiac/SCR_Mod#9]
https://www.steamcommunity.com/workshop/filedetails/discussion/2728183627/5733650980538137046/

The Incident Report and errors generated are located at the above link.

This is the first time that I have ever had fun writing a bug report.

**Comment by DeeMainiac** [comment]
ty for the report!

This issue probably occurs with other similar SCPs (SCP-1675 and SCP-3033-1/2). I Have not recreated this issue yet, but soon I imagine.

**Comment by DeeMainiac** [comment]
Should be fixed in time the next update on steam.
